name = "Beautiful Hugo Jost"
license = "MIT"
licenselink = "https://github.com/yannpeng/beautiful-hugo-jost/blob/master/LICENSE"
description = "An adaptation of the Beautiful Jekyll theme"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
features = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
min_version = 0.48

[author]
    name = "halogenica"
    homepage = "http://halogenica.net"

# If Porting existing theme
[original]
    author =  "halogenica"
    homepage = "http://halogenica.net"
    repo = "https://github.com/halogenica/beautifulhugo"
